#!/bin/bash

# Get example data and set up for use
curl -OL https://www.gstatic.com/alphafoldserver/examplefold_pdb_7bbv/examplefold_pdb_7bbv.zip
mkdir examplefold_pdb_7bbv
mv examplefold_pdb_7bbv.zip examplefold_pdb_7bbv/
cd examplefold_pdb_7bbv
unzip -o examplefold_pdb_7bbv.zip
%cd ~